version: "3.8"
services:
    db:
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD
        ports:
            - "5434:5432"
    s3:
        image: minio/minio:RELEASE.2020-10-18T21-54-12Z
        command: "server /data"
        environment:
            - MINIO_ACCESS_KEY
            - MINIO_SECRET_KEY
        ports:
            - "9002:9000"
